name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & build
        run: |
          set -euo pipefail
          npm ci
          npm run build
          # Normalize common output locations to repo root
          if [ -f build/main.js ]; then mv -f build/main.js ./main.js; fi
          if [ -f dist/main.js ]; then mv -f dist/main.js ./main.js; fi

      - name: Verify required files
        run: |
          set -euo pipefail
          test -f manifest.json || (echo "manifest.json missing" && exit 1)
          test -f main.js || (echo "main.js missing (build did not produce it)" && exit 1)

      - name: Package release assets
        id: package
        run: |
          set -euo pipefail
          rm -rf release
          mkdir -p release
          cp manifest.json release/
          cp main.js release/

          asset_list=$'release/manifest.json\nrelease/main.js'
          styles_present=0
          if [ -f styles.css ]; then
            cp styles.css release/
            asset_list="$asset_list"$'\nrelease/styles.css'
            styles_present=1
          fi

          cd release
          if [ "$styles_present" -eq 1 ]; then
            zip -r "${GITHUB_REPOSITORY#*/}.zip" manifest.json main.js styles.css
          else
            zip -r "${GITHUB_REPOSITORY#*/}.zip" manifest.json main.js
          fi
          cd ..

          asset_list="$asset_list"$'\nrelease/'"${GITHUB_REPOSITORY#*/}.zip"
          {
            echo 'asset_list<<EOF'
            echo "$asset_list"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.asset_list }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
